GET http://localhost:3004/players

###
POST http://localhost:3004/players

###
GET http://localhost:3004/players/1

###
PUT http://localhost:3004/players/24

###
DELETE http://localhost:3004/players/24